command: fix regression in /email
This regular expression was changed to a string.

Addresses the following failure:

==== TORN.SPACE ERROR REPORT ====
Error Time: Mon Jul 19 2021 10:43:02 GMT-0400 (Eastern Daylight Time)
Event: chat
Stack Trace: TypeError: valid_email_regex.test is not a function
    at Command.invoke (/home/torn/Torn/server_src/command.js:226:28)
    at runCommand (/home/torn/Torn/server_src/netcode.js:62:17)
    at /home/torn/Torn/server_src/netcode.js:408:17
    at Socket.<anonymous> (/home/torn/Torn/server_src/netcode.js:141:21)
    at Socket.emit (node:events:394:28)
    at Socket.emitUntyped (/home/torn/Torn/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/torn/Torn/node_modules/socket.io/dist/socket.js:428:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)